/* ============================================================
   TOOLSTACK — DATA FILE
   ------------------------------------------------------------
   All tool data lives here. To add a tool, append an object to
   TOOLS. To add a category, append to CATEGORIES.

   Scoring attributes per tool (score is computed in app.js):
     pricing : "free" (+2) | "freemium" (+1)
     noSignup: true (+2)  — usable without an account
     privacy : true (+2)  — local processing / privacy-friendly
     ads     : "none" (+2) | "some" (+1) | "heavy" (+0)
     ease    : 1..2       — ease of use
   Max score: 10
   ============================================================ */

const CATEGORIES = [
  // ---- Documents & Office ----
  { id: "pdf", name: "PDF Tools", group: "Documents & Office",
    icon: '<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/><path d="M9 13h6M9 16h6"/>' },
  { id: "doc", name: "Document Converters", group: "Documents & Office",
    icon: '<path d="M5 4h9l3 3v13H5z"/><path d="M14 4v3h3"/><path d="M8 11h6M8 14h6M8 17h4"/>' },
  { id: "sheet", name: "Spreadsheet Tools", group: "Documents & Office",
    icon: '<rect x="4" y="5" width="16" height="14"/><path d="M4 10h16M4 14h16M10 5v14"/>' },
  { id: "slides", name: "Presentation Tools", group: "Documents & Office",
    icon: '<rect x="3" y="4" width="18" height="12"/><path d="M12 16v4M8 20h8"/><path d="M8 12v-2M12 12V8M16 12v-4"/>' },
  { id: "ebook", name: "E-book Converters", group: "Documents & Office",
    icon: '<path d="M12 6c-2-1.5-4.5-2-8-2v14c3.5 0 6 .5 8 2 2-1.5 4.5-2 8-2V4c-3.5 0-6 .5-8 2z"/><path d="M12 6v14"/>' },
  { id: "ocr", name: "OCR & Text Extraction", group: "Documents & Office",
    icon: '<path d="M4 8V4h4M20 8V4h-4M4 16v4h4M20 16v4h-4"/><path d="M9 15l3-7 3 7M10.2 13h3.6"/>' },

  // ---- Media: Image ----
  { id: "imgconv", name: "Image Converters", group: "Media — Image",
    icon: '<rect x="3" y="5" width="13" height="11"/><circle cx="7.5" cy="9" r="1.2"/><path d="M3 14l4-3 4 3 2-1.5 3 2.5"/><path d="M17 12h4m0 0-2-2m2 2-2 2"/>' },
  { id: "imgcompress", name: "Image Compression", group: "Media — Image",
    icon: '<rect x="5" y="5" width="14" height="14"/><path d="M9 12h6"/><path d="M9 12l2-2M9 12l2 2M15 12l-2-2M15 12l-2 2"/>' },
  { id: "imgedit", name: "Image Editing", group: "Media — Image",
    icon: '<path d="M7 3v14h14"/><path d="M3 7h14v14"/><circle cx="12" cy="12" r="2.5"/>' },
  { id: "svg", name: "Icon & SVG Tools", group: "Media — Image",
    icon: '<circle cx="5" cy="19" r="2"/><circle cx="19" cy="5" r="2"/><path d="M7 17C10 14 14 10 17 7"/><path d="M5 5l2 2M17 17l2 2"/>' },

  // ---- Media: Audio & Video ----
  { id: "audioconv", name: "Audio Converters", group: "Media — Audio & Video",
    icon: '<path d="M9 18V6l8-2v12"/><circle cx="7" cy="18" r="2"/><circle cx="15" cy="16" r="2"/>' },
  { id: "audioedit", name: "Audio Editing", group: "Media — Audio & Video",
    icon: '<path d="M4 10v4M8 7v10M12 4v16M16 8v8M20 11v2"/>' },
  { id: "videoconv", name: "Video Converters", group: "Media — Audio & Video",
    icon: '<rect x="3" y="6" width="13" height="12"/><path d="M16 10l5-3v10l-5-3"/>' },
  { id: "videoedit", name: "Video Editing & Compression", group: "Media — Audio & Video",
    icon: '<rect x="3" y="5" width="18" height="14"/><path d="M7 5v14M17 5v14M3 9h4M3 15h4M17 9h4M17 15h4"/>' },
  { id: "screen", name: "Screen Recording & Screenshots", group: "Media — Audio & Video",
    icon: '<rect x="3" y="4" width="18" height="13"/><path d="M12 17v3M8 20h8"/><circle cx="12" cy="10.5" r="2.5"/>' },

  // ---- Files & Archives ----
  { id: "archive", name: "Archive & Compression", group: "Files & Archives",
    icon: '<path d="M6 3h12v18H6z"/><path d="M12 3v2M12 7v2M12 11v2"/><rect x="10.5" y="14" width="3" height="4"/>' },
  { id: "transfer", name: "File Transfer & Sharing", group: "Files & Archives",
    icon: '<path d="M8 17l-4-4 4-4"/><path d="M4 13h9"/><path d="M16 7l4 4-4 4"/><path d="M20 11h-6"/>' },
  { id: "universal", name: "Universal File Converters", group: "Files & Archives",
    icon: '<path d="M20 12a8 8 0 0 1-14.5 4.6"/><path d="M4 12a8 8 0 0 1 14.5-4.6"/><path d="M4 17v-4h4M20 7v4h-4"/>' },

  // ---- Data & Code ----
  { id: "data", name: "Data Format Tools", group: "Data & Code",
    icon: '<path d="M9 4c-2 0-3 1-3 3v2c0 1.5-1 2.5-2.5 3C5 12.5 6 13.5 6 15v2c0 2 1 3 3 3"/><path d="M15 4c2 0 3 1 3 3v2c0 1.5 1 2.5 2.5 3-1.5.5-2.5 1.5-2.5 3v2c0 2-1 3-3 3"/>' },
  { id: "code", name: "Code Formatters & Beautifiers", group: "Data & Code",
    icon: '<path d="M8 6l-5 6 5 6M16 6l5 6-5 6"/><path d="M13.5 4l-3 16"/>' },
  { id: "regex", name: "Regex Tools", group: "Data & Code",
    icon: '<path d="M15 4v8M11.5 6l7 4M18.5 6l-7 4"/><rect x="4" y="15" width="4" height="4"/>' },
  { id: "encode", name: "Encoding & Decoding", group: "Data & Code",
    icon: '<rect x="3" y="4" width="7" height="7"/><rect x="14" y="13" width="7" height="7"/><path d="M14 7h4v3M10 17H6v-3"/>' },
  { id: "hash", name: "Hash & Checksum", group: "Data & Code",
    icon: '<path d="M9 4L7 20M17 4l-2 16M5 9h15M4 15h15"/>' },
  { id: "devutil", name: "Developer Utilities", group: "Data & Code",
    icon: '<path d="M14.5 6.5a4 4 0 0 0-5.4 5L4 16.6V20h3.4l5.1-5.1a4 4 0 0 0 5-5.4l-2.8 2.8-2.4-.6-.6-2.4z"/>' },
  { id: "network", name: "Network & DNS Tools", group: "Data & Code",
    icon: '<circle cx="12" cy="12" r="8.5"/><path d="M3.5 12h17M12 3.5c2.5 2.3 3.8 5.2 3.8 8.5s-1.3 6.2-3.8 8.5c-2.5-2.3-3.8-5.2-3.8-8.5s1.3-6.2 3.8-8.5z"/>' },

  // ---- AI & Machine Learning ----
  { id: "aitext", name: "AI Writing & Summarizers", group: "AI & Machine Learning",
    icon: '<path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/><circle cx="12" cy="12" r="3"/>' },
  { id: "aiimage", name: "AI Image & Visual Tools", group: "AI & Machine Learning",
    icon: '<path d="M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z"/>' },
  { id: "aicode", name: "AI Code & Logic Helpers", group: "AI & Machine Learning",
    icon: '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M9 9l3 3-3 3M15 15h-2"/>' },

  // ---- CSS & Web Design ----
  { id: "cssgen", name: "CSS & Layout Generators", group: "CSS & Web Design",
    icon: '<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/>' },

  // ---- Generators & Converters ----
  { id: "qr", name: "QR & Barcode Generators", group: "Generators & Converters",
    icon: '<rect x="4" y="4" width="6" height="6"/><rect x="14" y="4" width="6" height="6"/><rect x="4" y="14" width="6" height="6"/><path d="M14 14h3v3h-3zM20 14v2M17 20h3M14 19v1"/>' },
  { id: "unit", name: "Unit Converters", group: "Generators & Converters",
    icon: '<rect x="2.5" y="9" width="19" height="6" transform="rotate(-8 12 12)"/><path d="M7 9.3l.7 2.5M11 8.7l.7 2.5M15 8.2l.7 2.5"/>' },
  { id: "currency", name: "Currency Converters", group: "Generators & Converters",
    icon: '<circle cx="12" cy="12" r="8.5"/><path d="M12 6.5v11M15 8.5c-.6-1-1.7-1.5-3-1.5-1.8 0-3 1-3 2.5s1.2 2 3 2.5 3 1 3 2.5-1.2 2.5-3 2.5c-1.3 0-2.4-.5-3-1.5"/>' },
  { id: "color", name: "Color Tools", group: "Generators & Converters",
    icon: '<path d="M12 3.5S5.5 10 5.5 14.5a6.5 6.5 0 0 0 13 0C18.5 10 12 3.5 12 3.5z"/><path d="M12 18a3.5 3.5 0 0 1-3.5-3.5"/>' },
  { id: "font", name: "Font & Typography Tools", group: "Generators & Converters",
    icon: '<path d="M5 19L11 5h2l6 14"/><path d="M7.5 14h9"/><path d="M4 19h4M16 19h4"/>' },

  // ---- Security & Privacy ----
  { id: "privacy", name: "Privacy & Metadata Tools", group: "Security & Privacy",
    icon: '<path d="M12 3l8 3v6c0 4.5-3.5 7.5-8 9-4.5-1.5-8-4.5-8-9V6z"/><path d="M9 12l2 2 4-4"/>' },
  { id: "password", name: "Password & Security Tools", group: "Security & Privacy",
    icon: '<rect x="5" y="10" width="14" height="10"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/><path d="M12 14v3"/>' },
  { id: "tempmail", name: "Temporary Mail & Masking", group: "Security & Privacy",
    icon: '<path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><path d="M22 6l-10 7L2 6"/>' }
];

const RAW_TOOLS = [
  /* ---------------- PDF Tools ---------------- */
  { name: "iLovePDF", cat: "pdf", url: "https://www.ilovepdf.com",
    desc: "Merge, split, compress, convert and sign PDFs with one of the most complete free PDF suites.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Smallpdf", cat: "pdf", url: "https://smallpdf.com",
    desc: "Polished all-in-one PDF toolkit — compress, convert, edit and e-sign with daily free usage.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "PDF24 Tools", cat: "pdf", url: "https://tools.pdf24.org",
    desc: "Fully free suite of 30+ PDF tools with no file limits, from a long-trusted German maker.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Sejda PDF", cat: "pdf", url: "https://www.sejda.com",
    desc: "Clean PDF editor and toolkit that actually lets you edit text inside PDFs for free daily.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "PDF Candy", cat: "pdf", url: "https://pdfcandy.com",
    desc: "47 PDF tools in one place — OCR, conversion, editing — with a generous free tier.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Stirling PDF", cat: "pdf", url: "https://www.stirlingpdf.com",
    desc: "Open-source, self-hostable PDF power tools — the privacy-maximalist choice.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 1 },

  /* ---------------- Document Converters ---------------- */
  { name: "CloudConvert", cat: "doc", url: "https://cloudconvert.com",
    desc: "High-quality conversion across 200+ formats including DOCX, ODT, RTF and Pages.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Zamzar", cat: "doc", url: "https://www.zamzar.com",
    desc: "Veteran file converter running since 2006 — handles nearly any document format.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Online2PDF", cat: "doc", url: "https://online2pdf.com",
    desc: "Free multi-file document-to-PDF conversion with merging, compression and unlocking.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 1 },
  { name: "FreeConvert", cat: "doc", url: "https://www.freeconvert.com",
    desc: "Big free conversion platform with a 1 GB file limit and fine-grained output options.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Google Docs", cat: "doc", url: "https://docs.google.com",
    desc: "Opens and exports DOCX, ODT, RTF and PDF for free — a dependable converter of last resort.",
    pricing: "free", noSignup: false, privacy: false, ads: "none", ease: 2 },

  /* ---------------- Spreadsheet Tools ---------------- */
  { name: "TableConvert", cat: "sheet", url: "https://tableconvert.com",
    desc: "Convert tables between Excel, CSV, JSON, Markdown, SQL and LaTeX in the browser.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "ConvertCSV", cat: "sheet", url: "https://www.convertcsv.com",
    desc: "Swiss-army CSV toolkit — CSV to JSON, SQL, XML and back, with in-browser processing.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 1 },
  { name: "CSVJSON", cat: "sheet", url: "https://csvjson.com",
    desc: "Minimal, fast CSV-to-JSON and JSON-to-CSV converter loved by developers.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Google Sheets", cat: "sheet", url: "https://sheets.google.com",
    desc: "Free spreadsheet editor that imports and exports XLSX, ODS and CSV reliably.",
    pricing: "free", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "Zoho Sheet", cat: "sheet", url: "https://www.zoho.com/sheet",
    desc: "Full-featured free online spreadsheet with strong Excel compatibility and a viewer.",
    pricing: "free", noSignup: false, privacy: false, ads: "none", ease: 2 },

  /* ---------------- Presentation Tools ---------------- */
  { name: "Google Slides", cat: "slides", url: "https://slides.google.com",
    desc: "Free presentation editor that opens and exports PPTX — great for quick conversions.",
    pricing: "free", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "Canva", cat: "slides", url: "https://www.canva.com",
    desc: "Design-forward presentation maker with a huge free tier and PPTX/PDF export.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "Convertio Presentations", cat: "slides", url: "https://convertio.co/ppt-pdf/",
    desc: "Convert PPT, PPTX, KEY and ODP between formats without installing anything.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Online-Convert Presentation", cat: "slides", url: "https://document.online-convert.com",
    desc: "Detailed presentation and document conversion with advanced output settings.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "heavy", ease: 1 },
  { name: "Pitch", cat: "slides", url: "https://pitch.com",
    desc: "Modern collaborative deck builder with a capable free plan and PDF/PPTX export.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },

  /* ---------------- E-book Converters ---------------- */
  { name: "Convertio E-book", cat: "ebook", url: "https://convertio.co/epub-mobi/",
    desc: "Convert EPUB, MOBI, AZW3, FB2 and PDF e-book formats in a couple of clicks.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Online-Convert E-book", cat: "ebook", url: "https://ebook.online-convert.com",
    desc: "Dedicated e-book converter targeting every major reader, including Kindle formats.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "heavy", ease: 1 },
  { name: "CloudConvert E-book", cat: "ebook", url: "https://cloudconvert.com/epub-converter",
    desc: "Reliable EPUB/MOBI/AZW3 conversion powered by Calibre under the hood.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Zamzar E-book", cat: "ebook", url: "https://www.zamzar.com/convert/epub-to-mobi/",
    desc: "Straightforward e-book format swapping with email or direct download delivery.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "EPUB.to", cat: "ebook", url: "https://epub.to",
    desc: "Focused EPUB conversion hub — EPUB to PDF, MOBI, AZW3 and back again.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },

  /* ---------------- OCR & Text Extraction ---------------- */
  { name: "OnlineOCR.net", cat: "ocr", url: "https://www.onlineocr.net",
    desc: "Free OCR for images and PDFs in 46 languages, exporting to Word, Excel or text.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "i2OCR", cat: "ocr", url: "https://www.i2ocr.com",
    desc: "Free multi-language OCR supporting 100+ languages with side-by-side review.",
    pricing: "free", noSignup: true, privacy: false, ads: "heavy", ease: 1 },
  { name: "OCR.space", cat: "ocr", url: "https://ocr.space",
    desc: "No-frills OCR with a free API tier — a favorite for quick text extraction jobs.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 1 },
  { name: "PDF24 OCR", cat: "ocr", url: "https://tools.pdf24.org/en/ocr-pdf",
    desc: "Make scanned PDFs searchable for free, with no page limits or watermarks.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "NewOCR", cat: "ocr", url: "https://www.newocr.com",
    desc: "Simple free OCR service that handles low-quality scans and 100+ languages.",
    pricing: "free", noSignup: true, privacy: false, ads: "heavy", ease: 1 },

  /* ---------------- Image Converters ---------------- */
  { name: "Squoosh", cat: "imgconv", url: "https://squoosh.app",
    desc: "Google's open-source image converter — WebP, AVIF, MozJPEG — processed entirely locally.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Convertio Images", cat: "imgconv", url: "https://convertio.co/image-converter/",
    desc: "Convert between PNG, JPG, WebP, HEIC, TIFF and dozens more image formats.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "EZGIF", cat: "imgconv", url: "https://ezgif.com",
    desc: "The GIF workhorse — convert, resize, optimize and edit GIFs, WebP and APNG.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "HEICtoJPEG", cat: "imgconv", url: "https://heictojpg.com",
    desc: "Drag-and-drop iPhone HEIC photos and get JPEGs back instantly, free.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "AVIF.io", cat: "imgconv", url: "https://avif.io",
    desc: "Free client-side AVIF converter — your images never leave the browser.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },

  /* ---------------- Image Compression ---------------- */
  { name: "TinyPNG", cat: "imgcompress", url: "https://tinypng.com",
    desc: "The classic smart lossy compressor for PNG, JPEG, WebP and AVIF — great results, zero effort.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Squoosh Compress", cat: "imgcompress", url: "https://squoosh.app",
    desc: "Side-by-side quality slider with full codec control, all processed on-device.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Compressor.io", cat: "imgcompress", url: "https://compressor.io",
    desc: "Lossy and lossless compression for JPEG, PNG, SVG, GIF and WebP up to 10 MB free.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Optimizilla", cat: "imgcompress", url: "https://imagecompressor.com",
    desc: "Batch-compress up to 20 images with a live quality preview slider.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "ShortPixel", cat: "imgcompress", url: "https://shortpixel.com/online-image-compression",
    desc: "Pro-grade compression engine with a free online tool and generous monthly quota.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },

  /* ---------------- Image Editing ---------------- */
  { name: "Photopea", cat: "imgedit", url: "https://www.photopea.com",
    desc: "A free Photoshop clone in the browser — opens PSD, XCF, Sketch and RAW, runs locally.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 1 },
  { name: "Pixlr", cat: "imgedit", url: "https://pixlr.com",
    desc: "Approachable layer-based photo editor with AI tools and a solid free tier.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "remove.bg", cat: "imgedit", url: "https://www.remove.bg",
    desc: "One-click AI background removal — the standard for cutting out subjects fast.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "upscale.media", cat: "imgedit", url: "https://www.upscale.media",
    desc: "Free AI image upscaling up to 4x that keeps details surprisingly crisp.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Fotor", cat: "imgedit", url: "https://www.fotor.com",
    desc: "Quick photo fixes, collages and effects without a learning curve.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },

  /* ---------------- Icon & SVG Tools ---------------- */
  { name: "SVGOMG", cat: "svg", url: "https://jakearchibald.github.io/svgomg/",
    desc: "The definitive SVGO web GUI — optimize SVGs with live preview, fully client-side.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "RealFaviconGenerator", cat: "svg", url: "https://realfavicongenerator.net",
    desc: "Generate a complete cross-platform favicon package from a single image.",
    pricing: "free", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "favicon.io", cat: "svg", url: "https://favicon.io",
    desc: "Instant favicons from text, emoji or images — dead simple and free.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "SVG Repo", cat: "svg", url: "https://www.svgrepo.com",
    desc: "500,000+ open-licensed SVG icons and vectors, searchable and editable in-browser.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Vectorizer.AI", cat: "svg", url: "https://vectorizer.ai",
    desc: "AI-powered bitmap-to-vector tracing that produces remarkably clean SVGs.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Iconify", cat: "svg", url: "https://icon-sets.iconify.design",
    desc: "Browse 200,000+ icons from every major open icon set in one unified explorer.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },

  /* ---------------- Audio Converters ---------------- */
  { name: "Online Audio Converter", cat: "audioconv", url: "https://online-audio-converter.com",
    desc: "123apps' converter for MP3, WAV, FLAC, OGG and M4A with bitrate control.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "CloudConvert Audio", cat: "audioconv", url: "https://cloudconvert.com/audio-converter",
    desc: "High-fidelity audio conversion with detailed codec and bitrate options.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Convertio Audio", cat: "audioconv", url: "https://convertio.co/audio-converter/",
    desc: "Fast browser audio conversion across 50+ formats, no install needed.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "FreeConvert Audio", cat: "audioconv", url: "https://www.freeconvert.com/audio-converter",
    desc: "Free audio conversion up to 1 GB with volume and channel adjustments.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Zamzar Audio", cat: "audioconv", url: "https://www.zamzar.com/convert/wav-to-mp3/",
    desc: "Trusted conversion between every mainstream audio format since 2006.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },

  /* ---------------- Audio Editing ---------------- */
  { name: "AudioMass", cat: "audioedit", url: "https://audiomass.co",
    desc: "Open-source waveform editor that runs 100% in your browser — nothing is uploaded.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 1 },
  { name: "TwistedWave Online", cat: "audioedit", url: "https://twistedwave.com/online",
    desc: "Serious browser audio editor with effects, normalization and precise editing.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Vocal Remover", cat: "audioedit", url: "https://vocalremover.org",
    desc: "AI vocal/instrumental separation plus a pitch changer, cutter and key finder — free.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Audio Trimmer", cat: "audioedit", url: "https://audiotrimmer.com",
    desc: "Cut and fade audio files in seconds without touching an account form.",
    pricing: "free", noSignup: true, privacy: false, ads: "heavy", ease: 2 },
  { name: "MP3Cut", cat: "audioedit", url: "https://mp3cut.net",
    desc: "123apps' trimmer — cut ringtones and clips with fade in/out, free and quick.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },

  /* ---------------- Video Converters ---------------- */
  { name: "CloudConvert Video", cat: "videoconv", url: "https://cloudconvert.com/video-converter",
    desc: "Quality-focused MP4, WebM and MKV conversion with codec-level control.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Cobalt", cat: "videoconv", url: "https://cobalt.tools",
    desc: "Minimalist, zero-ad media downloader for YouTube, Vimeo, TikTok, Twitter and Reddit.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "EZGIF Video", cat: "videoconv", url: "https://ezgif.com/video-to-gif",
    desc: "Video-to-GIF and GIF-to-video conversion with frame-accurate trimming.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "FreeConvert Video", cat: "videoconv", url: "https://www.freeconvert.com/video-converter",
    desc: "Convert video up to 1 GB free with resolution, codec and bitrate options.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Convertio Video", cat: "videoconv", url: "https://convertio.co/video-converter/",
    desc: "Browser video conversion across 300+ format pairs — simple and dependable.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Online-Convert Video", cat: "videoconv", url: "https://video.online-convert.com",
    desc: "Target-device presets and fine settings for every common video format.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "heavy", ease: 1 },

  /* ---------------- Video Editing & Compression ---------------- */
  { name: "Clideo", cat: "videoedit", url: "https://clideo.com",
    desc: "Simple online suite to trim, merge, compress and resize video for any platform.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Kapwing", cat: "videoedit", url: "https://www.kapwing.com",
    desc: "Collaborative browser video editor with subtitles, resizing and meme-grade speed.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "VEED.io", cat: "videoedit", url: "https://www.veed.io",
    desc: "Full-featured online editor with auto-subtitles, filters and screen recording.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "Clipchamp", cat: "videoedit", url: "https://clipchamp.com",
    desc: "Microsoft's free browser editor — timeline editing with local processing.",
    pricing: "freemium", noSignup: false, privacy: true, ads: "none", ease: 2 },
  { name: "FreeConvert Video Compressor", cat: "videoedit", url: "https://www.freeconvert.com/video-compressor",
    desc: "Compress video to a target size or quality — up to 1 GB free per file.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },

  /* ---------------- Screen Recording & Screenshots ---------------- */
  { name: "RecordScreen.io", cat: "screen", url: "https://recordscreen.io",
    desc: "Record screen and camera entirely in-browser — video never leaves your machine.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Loom", cat: "screen", url: "https://www.loom.com",
    desc: "The async-video standard — record, host and share screen recordings instantly.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "Screencastify", cat: "screen", url: "https://www.screencastify.com",
    desc: "Chrome-based screen recorder popular in education, with a usable free plan.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "ScreenCapture.com", cat: "screen", url: "https://www.screencapture.com",
    desc: "Zero-install online screen recorder with system audio and webcam overlay.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Vimeo Record", cat: "screen", url: "https://vimeo.com/features/screen-recorder",
    desc: "Free unlimited screen recordings hosted directly on your Vimeo account.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },

  /* ---------------- Archive & Compression ---------------- */
  { name: "ezyZip", cat: "archive", url: "https://www.ezyzip.com",
    desc: "Zip and unzip archives directly in the browser — files are processed locally.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Extract.me", cat: "archive", url: "https://extract.me",
    desc: "Archive Extractor opens 70+ formats including RAR, 7z and password-protected files.",
    pricing: "free", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Unzip-Online", cat: "archive", url: "https://unzip-online.com",
    desc: "Bare-bones online unzipper for ZIP and RAR files up to 200 MB.",
    pricing: "free", noSignup: true, privacy: false, ads: "heavy", ease: 1 },
  { name: "CloudConvert Archive", cat: "archive", url: "https://cloudconvert.com/archive-converter",
    desc: "Convert between ZIP, 7Z, TAR and RAR extraction with quality infrastructure.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Online-Convert Archive", cat: "archive", url: "https://archive.online-convert.com",
    desc: "Create and convert compressed archives across all mainstream formats.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "heavy", ease: 1 },

  /* ---------------- File Transfer & Sharing ---------------- */
  { name: "WeTransfer", cat: "transfer", url: "https://wetransfer.com",
    desc: "The household name for sending big files — 2 GB free with zero friction.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Smash", cat: "transfer", url: "https://fromsmash.com",
    desc: "No file size limit on the free tier — send anything, of any size.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Wormhole", cat: "transfer", url: "https://wormhole.app",
    desc: "End-to-end encrypted file sharing with links that expire — up to 10 GB free.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Send Anywhere", cat: "transfer", url: "https://send-anywhere.com",
    desc: "Cross-device transfer using 6-digit keys — no account, no cloud residue.",
    pricing: "freemium", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "file.io", cat: "transfer", url: "https://www.file.io",
    desc: "Ephemeral file sharing — links self-destruct after download by default.",
    pricing: "freemium", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Snapdrop", cat: "transfer", url: "https://snapdrop.net",
    desc: "AirDrop for the web — instant local-network transfer between any devices.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },

  /* ---------------- Universal File Converters ---------------- */
  { name: "CloudConvert Universal", cat: "universal", url: "https://cloudconvert.com",
    desc: "200+ formats, API access, and consistently high output quality — the benchmark.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Convertio Universal", cat: "universal", url: "https://convertio.co",
    desc: "300+ formats covering documents, media, fonts and archives in one place.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Zamzar Universal", cat: "universal", url: "https://www.zamzar.com",
    desc: "1,100+ conversion pairs and nearly two decades of reliability.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "FreeConvert Universal", cat: "universal", url: "https://www.freeconvert.com",
    desc: "Generous 1 GB free limit and advanced options across every file category.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Online-Convert Universal", cat: "universal", url: "https://www.online-convert.com",
    desc: "Deep settings for every conversion type, if you can tolerate the ads.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "heavy", ease: 1 },

  /* ---------------- Data Format Tools ---------------- */
  { name: "JSON Formatter", cat: "data", url: "https://jsonformatter.org",
    desc: "Format, validate and convert JSON with tree view and JSON-to-XML/CSV tools.",
    pricing: "free", noSignup: true, privacy: true, ads: "heavy", ease: 2 },
  { name: "JSONLint", cat: "data", url: "https://jsonlint.com",
    desc: "The classic JSON validator — paste, validate, locate the syntax error.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "JSON Crack", cat: "data", url: "https://jsoncrack.com",
    desc: "Visualize JSON, YAML and CSV as interactive node graphs — brilliant for debugging.",
    pricing: "freemium", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "YAML Lint", cat: "data", url: "https://www.yamllint.com",
    desc: "Instant YAML validation that catches indentation sins before your CI does.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "ConvertCSV Data", cat: "data", url: "https://www.convertcsv.com/csv-to-json.htm",
    desc: "CSV to JSON, SQL, XML and more with client-side processing options.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 1 },

  /* ---------------- Code Formatters & Beautifiers ---------------- */
  { name: "Prettier Playground", cat: "code", url: "https://prettier.io/playground/",
    desc: "The industry-standard formatter, live in the browser with every option exposed.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Beautifier.io", cat: "code", url: "https://beautifier.io",
    desc: "Open-source JS, HTML and CSS beautifier that also de-obfuscates minified code.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "CodeBeautify", cat: "code", url: "https://codebeautify.org",
    desc: "A giant grab-bag of formatters, minifiers and converters for 100+ languages.",
    pricing: "free", noSignup: true, privacy: true, ads: "heavy", ease: 1 },
  { name: "SQLFormat", cat: "code", url: "https://sqlformat.org",
    desc: "Clean, focused SQL formatting with a free API — no clutter whatsoever.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Minifier.org", cat: "code", url: "https://www.minifier.org",
    desc: "One-click JS and CSS minification when you need it fast and simple.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Transform Tools", cat: "code", url: "https://transform.tools",
    desc: "Polyglot code converter — JSON to TS, SVG to JSX, HTML to JSX, CSS to JS.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },

  /* ---------------- Regex Tools ---------------- */
  { name: "regex101", cat: "regex", url: "https://regex101.com",
    desc: "The definitive regex IDE — live matching, full explanation and a debugger.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "RegExr", cat: "regex", url: "https://regexr.com",
    desc: "Interactive regex learning and testing with community patterns and cheatsheet.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Debuggex", cat: "regex", url: "https://www.debuggex.com",
    desc: "Visualizes your regex as a railroad diagram — see exactly how it branches.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "iHateRegex", cat: "regex", url: "https://ihateregex.io",
    desc: "A searchable cookbook of battle-tested regex patterns with visual explanations.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Regex Tester", cat: "regex", url: "https://www.regextester.com",
    desc: "Quick pattern testing with a library of common community-submitted regexes.",
    pricing: "free", noSignup: true, privacy: true, ads: "heavy", ease: 2 },

  /* ---------------- Encoding & Decoding ---------------- */
  { name: "CyberChef", cat: "encode", url: "https://gchq.github.io/CyberChef/",
    desc: "GCHQ's 'cyber Swiss army knife' — chain 300+ encode/decode/crypto operations locally.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 1 },
  { name: "Base64Decode.org", cat: "encode", url: "https://www.base64decode.org",
    desc: "Fast Base64 encoding and decoding for text and files, nothing extra.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "URLDecoder.org", cat: "encode", url: "https://www.urldecoder.org",
    desc: "URL percent-encoding and decoding with support for every charset you'll meet.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "JWT.io", cat: "encode", url: "https://jwt.io",
    desc: "Auth0's JWT debugger — decode, verify and inspect JSON Web Tokens client-side.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "FreeFormatter Encoders", cat: "encode", url: "https://www.freeformatter.com/html-entities.html",
    desc: "HTML entities, URL, Base64 and string escaping utilities in one toolbox.",
    pricing: "free", noSignup: true, privacy: true, ads: "heavy", ease: 2 },

  /* ---------------- Hash & Checksum ---------------- */
  { name: "emn178 Online Tools", cat: "hash", url: "https://emn178.github.io/online-tools/",
    desc: "SHA-256, SHA-512, MD5 and more for text and files — computed entirely in-browser.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "CyberChef Hashing", cat: "hash", url: "https://gchq.github.io/CyberChef/#recipe=SHA2('256',64,160)",
    desc: "Every hash algorithm you can name, chainable with other operations, all local.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 1 },
  { name: "Online-Convert Hash", cat: "hash", url: "https://hash.online-convert.com",
    desc: "Generate MD5, SHA and CRC checksums from text or uploaded files.",
    pricing: "free", noSignup: true, privacy: false, ads: "heavy", ease: 2 },
  { name: "MD5 Hash Generator", cat: "hash", url: "https://www.md5hashgenerator.com",
    desc: "Dead-simple MD5 generation for quick, non-cryptographic checksum needs.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "VirusTotal", cat: "hash", url: "https://www.virustotal.com",
    desc: "Look up a file hash against 70+ antivirus engines — verify before you trust.",
    pricing: "free", noSignup: true, privacy: false, ads: "none", ease: 2 },

  /* ---------------- Developer Utilities ---------------- */
  { name: "UUID Generator", cat: "devutil", url: "https://www.uuidgenerator.net",
    desc: "Bulk-generate v1/v4/v7 UUIDs with an API for scripting.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Crontab Guru", cat: "devutil", url: "https://crontab.guru",
    desc: "The cron schedule decoder ring — plain-English explanations of any expression.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Epoch Converter", cat: "devutil", url: "https://www.epochconverter.com",
    desc: "Unix timestamp conversion in every direction, with code snippets per language.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Diffchecker", cat: "devutil", url: "https://www.diffchecker.com",
    desc: "Compare text, images, PDFs and folders with clean side-by-side diffs.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Mockaroo", cat: "devutil", url: "https://www.mockaroo.com",
    desc: "Generate realistic mock datasets in CSV, JSON or SQL — up to 1,000 rows free.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "JSONPlaceholder", cat: "devutil", url: "https://jsonplaceholder.typicode.com",
    desc: "Free fake REST API for prototyping — the default test endpoint of the web.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },

  /* ---------------- Network & DNS Tools ---------------- */
  { name: "DNSChecker", cat: "network", url: "https://dnschecker.org",
    desc: "Check DNS propagation across global locations, plus 50+ network utilities.",
    pricing: "free", noSignup: true, privacy: true, ads: "heavy", ease: 2 },
  { name: "MXToolbox", cat: "network", url: "https://mxtoolbox.com",
    desc: "The email-admin standard — MX, SPF, DKIM, blacklist and DNS diagnostics.",
    pricing: "freemium", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "ipinfo.io", cat: "network", url: "https://ipinfo.io",
    desc: "Clean IP geolocation and ASN lookup with a generous free API.",
    pricing: "freemium", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Ping.eu", cat: "network", url: "https://ping.eu",
    desc: "Ping, traceroute, port check and whois from an external vantage point.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 1 },
  { name: "Security Headers", cat: "network", url: "https://securityheaders.com",
    desc: "Grade any site's HTTP security headers and learn how to fix them.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "WhatIsMyIPAddress", cat: "network", url: "https://whatismyipaddress.com",
    desc: "Your public IP, location and connection details at a glance.",
    pricing: "free", noSignup: true, privacy: false, ads: "heavy", ease: 2 },

  /* ---------------- AI & Machine Learning ---------------- */
  { name: "ChatGPT (Free Tier)", cat: "aitext", url: "https://chatgpt.com",
    desc: "OpenAI's flagship conversational AI model for writing, brainstorming, editing, and code helper.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "Claude.ai", cat: "aitext", url: "https://claude.ai",
    desc: "Anthropic's AI model known for nuanced writing, long context comprehension, and accurate coding.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },
  { name: "Hugging Face Spaces", cat: "aiimage", url: "https://huggingface.co/spaces",
    desc: "Thousands of free open-source AI web apps, image generators (FLUX, SDXL), and voice clones.",
    pricing: "free", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "v0.dev by Vercel", cat: "aicode", url: "https://v0.dev",
    desc: "Generative UI system by Vercel — generate React, Tailwind, and HTML components from text prompts.",
    pricing: "freemium", noSignup: false, privacy: false, ads: "none", ease: 2 },

  /* ---------------- CSS & Web Design ---------------- */
  { name: "CSS Grid Generator", cat: "cssgen", url: "https://cssgrid-generator.netlify.app",
    desc: "Visual editor to create complex CSS Grid layouts with column/row gap sliders and instant code export.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Fancy Border Radius", cat: "cssgen", url: "https://9elements.github.io/fancy-border-radius/",
    desc: "Visual generator for organic, blobby modern CSS 8-value border-radius shapes.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Realtime Colors", cat: "color", url: "https://www.realtimecolors.com",
    desc: "Visualize your color palette live on a complete mock website layout in real time.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },

  /* ---------------- QR & Barcode Generators ---------------- */
  { name: "QRCode Monkey", cat: "qr", url: "https://www.qrcode-monkey.com",
    desc: "Free high-resolution QR codes with logos and colors — no signup, no expiry.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "goQR.me", cat: "qr", url: "https://goqr.me",
    desc: "Straightforward QR generation with a free API for programmatic use.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "QR Code Generator", cat: "qr", url: "https://www.qr-code-generator.com",
    desc: "Polished QR creation with design options; dynamic codes require an account.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "TEC-IT Barcode Generator", cat: "qr", url: "https://barcode.tec-it.com",
    desc: "Generate EAN, UPC, Code 128 and 100+ barcode symbologies free.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 1 },
  { name: "ZXing Decoder", cat: "qr", url: "https://zxing.org/w/decode.jspx",
    desc: "Decode any QR or barcode image using the open-source ZXing engine.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 1 },

  /* ---------------- Unit Converters ---------------- */
  { name: "UnitConverters.net", cat: "unit", url: "https://www.unitconverters.net",
    desc: "Comprehensive converter covering length, mass, energy, data and 70+ categories.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "ConvertUnits.com", cat: "unit", url: "https://www.convertunits.com",
    desc: "Type any conversion in plain text and get an instant answer with the math shown.",
    pricing: "free", noSignup: true, privacy: true, ads: "heavy", ease: 2 },
  { name: "RapidTables", cat: "unit", url: "https://www.rapidtables.com",
    desc: "Conversion tables and calculators for electrical, math and everyday units.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Metric Conversions", cat: "unit", url: "https://www.metric-conversions.org",
    desc: "Clean metric/imperial conversion with printable reference charts.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Omni Calculator", cat: "unit", url: "https://www.omnicalculator.com",
    desc: "3,000+ specialized calculators — from unit conversion to orbital mechanics.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },

  /* ---------------- Currency Converters ---------------- */
  { name: "XE Currency", cat: "currency", url: "https://www.xe.com/currencyconverter/",
    desc: "The reference mid-market exchange rates, updated live for 130+ currencies.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Wise Converter", cat: "currency", url: "https://wise.com/us/currency-converter/",
    desc: "Real mid-market rates with historical charts and rate alerts.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "OANDA Converter", cat: "currency", url: "https://www.oanda.com/currency-converter/",
    desc: "Bank-grade FX rates with 25 years of historical data access.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "X-Rates", cat: "currency", url: "https://www.x-rates.com",
    desc: "Quick rate tables, monthly averages and historic charts for major currencies.",
    pricing: "free", noSignup: true, privacy: true, ads: "heavy", ease: 2 },
  { name: "Currency.wiki", cat: "currency", url: "https://currency.wiki",
    desc: "Minimal, fast currency conversion without the portal clutter.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },

  /* ---------------- Color Tools ---------------- */
  { name: "Coolors", cat: "color", url: "https://coolors.co",
    desc: "The fastest palette generator — press space, get schemes, export anywhere.",
    pricing: "freemium", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Adobe Color", cat: "color", url: "https://color.adobe.com",
    desc: "Color wheel, harmony rules, accessibility checks and trend palettes, free.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "WebAIM Contrast Checker", cat: "color", url: "https://webaim.org/resources/contrastchecker/",
    desc: "The canonical WCAG contrast checker for accessible text and UI colors.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "CSS Gradient", cat: "color", url: "https://cssgradient.io",
    desc: "Visual gradient builder that outputs clean, ready-to-paste CSS.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "ColorHexa", cat: "color", url: "https://www.colorhexa.com",
    desc: "Deep per-color encyclopedia — conversions, schemes, blindness simulation.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Color Hunt", cat: "color", url: "https://colorhunt.co",
    desc: "Curated, community-voted 4-color palettes for quick design inspiration.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },

  /* ---------------- Font & Typography Tools ---------------- */
  { name: "Google Fonts", cat: "font", url: "https://fonts.google.com",
    desc: "1,500+ open-source font families with pairing suggestions and easy embedding.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "WhatTheFont", cat: "font", url: "https://www.myfonts.com/pages/whatthefont",
    desc: "Upload an image and identify the font — the classic type-detective tool.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 2 },
  { name: "Font Squirrel Generator", cat: "font", url: "https://www.fontsquirrel.com/tools/webfont-generator",
    desc: "Convert desktop fonts into optimized @font-face webfont kits.",
    pricing: "free", noSignup: true, privacy: false, ads: "some", ease: 1 },
  { name: "Fontpair", cat: "font", url: "https://www.fontpair.co",
    desc: "Curated Google Font pairings previewed in real layouts.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Transfonter", cat: "font", url: "https://transfonter.org",
    desc: "Modern webfont converter — WOFF2, subsetting and CSS generation, free.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },

  /* ---------------- Privacy & Metadata Tools ---------------- */
  { name: "Jimpl", cat: "privacy", url: "https://jimpl.com",
    desc: "View and remove EXIF metadata from photos — see what your images reveal.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "VerExif", cat: "privacy", url: "https://www.verexif.com/en/",
    desc: "Check and strip EXIF data, including GPS location, in two clicks.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Metadata2Go", cat: "privacy", url: "https://www.metadata2go.com",
    desc: "Inspect metadata in images, video, audio and documents online.",
    pricing: "free", noSignup: true, privacy: false, ads: "heavy", ease: 2 },
  { name: "Image Scrubber", cat: "privacy", url: "https://everestpipkin.github.io/image-scrubber/",
    desc: "Open-source local tool that strips metadata and blurs/paints over identifying details.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "TheXifer", cat: "privacy", url: "https://www.thexifer.net",
    desc: "View, edit and geotag or de-geotag EXIF data in your photos.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 1 },
  { name: "ExifRemove", cat: "privacy", url: "https://exifremove.com",
    desc: "Strip hidden EXIF metadata (GPS location, camera model, timestamp) from images in browser.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },

  /* ---------------- Password & Security Tools ---------------- */
  { name: "Bitwarden Generator", cat: "password", url: "https://bitwarden.com/password-generator/",
    desc: "Strong password and passphrase generation from the open-source password manager.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Have I Been Pwned", cat: "password", url: "https://haveibeenpwned.com",
    desc: "Check whether your email or password appears in known data breaches.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "1Password Generator", cat: "password", url: "https://1password.com/password-generator",
    desc: "Random passwords, passphrases and PINs generated locally in your browser.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Security.org Strength Test", cat: "password", url: "https://www.security.org/how-secure-is-my-password/",
    desc: "Estimates how long a computer would take to crack your password.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Random.org", cat: "password", url: "https://www.random.org/passwords/",
    desc: "True atmospheric-noise randomness for passwords, numbers and strings.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Temp Mail", cat: "tempmail", url: "https://temp-mail.org",
    desc: "Disposable temporary email address generator to protect your main inbox from spam.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },

  /* ---------------- Hidden Gems & Discoveries ---------------- */
  { name: "Excalidraw", cat: "devutil", url: "https://excalidraw.com",
    desc: "Virtual collaborative whiteboard for sketching hand-drawn style diagrams, flowcharts, and wireframes.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Ray.so", cat: "code", url: "https://ray.so",
    desc: "Create beautiful, high-resolution code snippet screenshots with custom syntax themes and padding.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Carbon", cat: "code", url: "https://carbon.now.sh",
    desc: "Create and share beautiful images of your source code with customizable themes, fonts, and window frames.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Hoppscotch", cat: "devutil", url: "https://hoppscotch.io",
    desc: "Open-source lightweight API development client — test HTTP, WebSocket, GraphQL endpoints in-browser.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "DevToys Web", cat: "devutil", url: "https://devtoys.app",
    desc: "Swiss army knife for developers — inspect, encode, format, convert, and test data offline in browser.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Regex Vis", cat: "regex", url: "https://regex-vis.com",
    desc: "Visual editor and graphic regular expression diagram generator that lets you edit regex visually.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Haikei", cat: "svg", url: "https://haikei.app",
    desc: "Generate unique SVG shapes, organic blobs, waves, and background patterns for web design.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Get Waves", cat: "svg", url: "https://getwaves.io",
    desc: "Instant SVG wave generator to create smooth, customizable section dividers for websites.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Blobmaker", cat: "svg", url: "https://www.blobmaker.app",
    desc: "Generate random, organic SVG blob shapes with custom complexity and color sliders.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Hero Patterns", cat: "svg", url: "https://heropatterns.com",
    desc: "A collection of repeatable SVG background patterns for web designers and developers.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Goblin.tools", cat: "aitext", url: "https://goblin.tools",
    desc: "Collection of small AI tools to break down overwhelming tasks, rephrase tone, and estimate time.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "CleanUp.pictures", cat: "imgedit", url: "https://cleanup.pictures",
    desc: "AI-powered brush tool to instantly remove unwanted objects, text, defects, or people from photos.",
    pricing: "freemium", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "Unscreen", cat: "videoedit", url: "https://www.unscreen.com",
    desc: "Remove video backgrounds automatically 100% online without green screens or complex masking.",
    pricing: "freemium", noSignup: true, privacy: false, ads: "none", ease: 2 },
  { name: "Privnote", cat: "privacy", url: "https://privnote.com",
    desc: "Send confidential self-destructing notes that automatically erase after being read once.",
    pricing: "free", noSignup: true, privacy: true, ads: "some", ease: 2 },
  { name: "Password Pusher", cat: "password", url: "https://pwpush.com",
    desc: "Securely send passwords and secret payloads with expiring, single-use, self-destruct links.",
    pricing: "free", noSignup: true, privacy: true, ads: "none", ease: 2 },
  { name: "SimpleLogin", cat: "tempmail", url: "https://simplelogin.io",
    desc: "Open-source email alias manager to create masked email addresses and protect your main inbox.",
    pricing: "freemium", noSignup: false, privacy: true, ads: "none", ease: 2 },
  { name: "BandLab Web", cat: "audioedit", url: "https://www.bandlab.com",
    desc: "Full browser-based digital audio workstation (DAW) for multi-track recording, mixing, and production.",
    pricing: "free", noSignup: false, privacy: false, ads: "none", ease: 2 }
];

// Automatically generate unique IDs for every tool object
const TOOLS = RAW_TOOLS.map((t, idx) => {
  const slug = t.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  return {
    id: `${slug}-${t.cat}-${idx}`,
    ...t
  };
});
